### ISSUE TITLE
Trying to clarify the extra configuration and excluded namespaces list

### ISSUE THREAD

**Issue by SohamChakraborty** [caas-team/py-kube-downscaler#79] opened 2024-07-26 06:55 UTC
Hi,

Thank you for this project. I am currently evaluating this in a test environment and although downscaling works perfectly, upscaling didn't work out. Also the tool picked up namespaces that supposed to be excluded. I am providing my installation and configuration steps below so that any anomalies/mistakes can be identified and I can safely try this one out.

```
$ helm repo add caas-team https://caas-team.github.io/helm-charts/
$ helm fetch caas-team/py-kube-downscaler --version 0.2.4 --untar -d ./
$ helm template --release-name py-kube-downscaler ./py-kube-downscaler/ -n py-kube-downscaler --values values.yaml
$ helm install  py-kube-downscaler ./py-kube-downscaler/ -n py-kube-downscaler --values values.yaml --create-namespace
```
And here is `values.yaml`:

```
$ cat values.yaml 
rbac:
  create: true
arguments:
  - --include-resources=deployments
excludedNamespaces: ['argocd, deepfence-console, default, elastic-system, gadget, goldilocks, ingress-nginx, jenkins, kube-node-lease, kube-public, kube-system, prometheus, py-kube-downscaler']
extraConfig: |
  DOWNSCALE_PERIOD: "Mon-Sun 19:15-19:35 Asia/Kolkata"
  UPSCALE_PERIOD: "Mon-Sun 19:36-19:14 Asia/Kolkata"
```

I am quite sure that the `excludedNamespaces` list is wrong but I haven't tried it in this format yet:

```
excludedNamespaces: ['argocd', 'deepfence-console', 'default', 'elastic-system', ..., 'py-kube-downscaler']
```
What about the upscaling? 

I just want to downscale at a particular time and upscale on all times that doesn't match the downscale time. What's the correct syntax? 

And @samuel-esp is there a chat group yet? Mind making a slack channel in CNCF or Kubernetes slack?

Thanks,

**Comment by samuel-esp** [comment] 2024-07-26 07:23
Hi @SohamChakraborty, starting from the last question, we actually don't have a slack channel but it was proposed in #44, we can try to address this issue. For CNCF we could think about applying to be CNCF backed but the procedure won't be short I guess

To help us in debugging this 

1. Can you provide the logs of the Downscaler (preferably the Downscaler should have the --debug arg activated)
2. Can you provide the block of code that you are using, so we can test if we have a bug inside `UPSCALE_PERIOD`?

The problem you are facing might have been caused by this string in the `UPSCALE_PERIOD`
`Mon-Sun 19:36-19:14 Asia/Kolkata`

You should refactor it in this way:
`Mon-Sun 00:00-19:14 Asia/Kolkata,Mon-Sun 19:36-23:59 Asia/Kolkata`

KubeDownscaler can't compute syntax that overlaps 2 days like "i want it to be up and running from 18.00 of Day 1 to 17:55 of Day 2". Thank you for pointing out this doubt, I will try to be more specific inside the docs

For the other questions:

1. Regarding the `excludedNamespaces`, I would recommend using a regex and putting it inside the ConfigMap `EXCLUDE_NAMESPACES` env (explained in the docs)
2. Regarding the Uptime/Downtime. i would suggest only to use the `DEFAULT_DOWNTIME` annotation (for the time range not specified inside  `DEFAULT_DOWNTIME`, the targeted namespaces are up and running)

**Comment by SohamChakraborty** [comment] 2024-07-30 08:07
Hi @samuel-esp,

Thank you again for your reply. 

I managed to run some tests on a minikube cluster I created. I ran three scenarios which I will describe below:

# Scenario 1

```
$ cat values.yaml
rbac:
  create: true
arguments:
  - --include-resources=deployments
extraConfig: |
  EXCLUDE_NAMESPACES: "pr-1234,kube-system"
  DEFAULT_DOWNTIME: "Mon-Sun 11:25-11:35 Asia/Kolkata"
  DEFAULT_UPTIME: "Mon-Sun 00:00-11:24 Asia/Kolkata,Mon-Sun 11:36-00:00 Asia/Kolkata"
```
Since `DEFAULT_DOWNTIME` doesn't span over a day, I think this is correct. `DEFAULT_UPTIME` does span over a day and so I have modified it as you instructed.

Scale down works perfectly but scale up doesn't. Some snippets of the logs:

```
$ kubectl logs -f py-kube-downscaler-c578b7664-m6wk6 -n py-kube-downscaler
2024-07-30 05:50:58,707 INFO: Downscaler vdev started with admission_controller=, debug=False, default_downtime=Mon-Sun 11:25-11:35 Asia/Kolkata, default_uptime=Mon-Sun 00:00-11:24 Asia/Kolkata,Mon-Sun 11:36-00:00 Asia/Kolkata, deployment_time_annotation=None, downscale_period=never, downtime_replicas=0, dry_run=False, enable_events=False, exclude_deployments=py-kube-downscaler,kube-downscaler,downscaler, exclude_namespaces=pr-1234,kube-system, grace_period=900, include_resources=deployments, interval=30, matching_labels=, namespace=, once=False, upscale_period=never
2024-07-30 05:54:29,495 INFO: Scaling down Deployment pr-4321/nginx-pr-4321 from 2 to 0 replicas (uptime: Mon-Sun 00:00-11:24 Asia/Kolkata,Mon-Sun 11:36-00:00 Asia/Kolkata, downtime: Mon-Sun 11:25-11:35 Asia/Kolkata)
```

# Scenario 2:

I ran the same `values.yaml` after modifying the time range but with `debug` enabled. This time I captured the logs which I will attach. I ran this in `Asia/Kolkata` tz.

```
$ cat values.yaml 
rbac:
  create: true
arguments:
  - --include-resources=deployments
  - --debug
extraConfig: |
  EXCLUDE_NAMESPACES: "pr-1234,kube-system"
  DEFAULT_DOWNTIME: "Mon-Sun 12:15-12:20 Asia/Kolkata"
  DEFAULT_UPTIME: "Mon-Sun 00:00-12:14 Asia/Kolkata,Mon-Sun 12:21-00:00 Asia/Kolkata" 

$ kubectl get pods -A
NAMESPACE            NAME                                  READY   STATUS    RESTARTS      AGE
kube-system          coredns-bd6b6df9f-kqnfb               1/1     Running   1 (11h ago)   21h
kube-system          etcd-minikube                         1/1     Running   1 (11h ago)   21h
kube-system          kube-apiserver-minikube               1/1     Running   1 (88m ago)   21h
kube-system          kube-controller-manager-minikube      1/1     Running   1 (11h ago)   21h
kube-system          kube-proxy-tmsff                      1/1     Running   1 (11h ago)   21h
kube-system          kube-scheduler-minikube               1/1     Running   1 (88m ago)   21h
kube-system          storage-provisioner                   1/1     Running   3 (87m ago)   21h
pr-1234              nginx-deployment-9456bbbf9-h2fq2      1/1     Running   0             75m
pr-1234              nginx-deployment-9456bbbf9-jfqdk      1/1     Running   0             75m
pr-4321              nginx-pr-4321-5898bbdc5b-mpdr8        1/1     Running   0             22s
pr-4321              nginx-pr-4321-5898bbdc5b-zb59b        1/1     Running   0             22s
py-kube-downscaler   py-kube-downscaler-75f695875f-jjkwr   1/1     Running   0             3s
```
[kube-downscaler.log](https://github.com/user-attachments/files/16424325/kube-downscaler.log)

Again scale down works as advertised, but scale up doesn't.

# Scenario 3:

Maybe this is due to tz. So I changed to UTC timezone and repeated the experiment. Same results, i.e. downscale worked but upscale didn't.

```
$ cat values.yaml 
rbac:
  create: true
arguments:
  - --include-resources=deployments
  - --debug
extraConfig: |
  EXCLUDE_NAMESPACES: "pr-1234,kube-system"
  DEFAULT_DOWNTIME: "Mon-Sun 07:25-07:30 UTC"
  DEFAULT_UPTIME: "Mon-Sun 00:00-07:24 UTC,Mon-Sun 07:31-00:00 UTC" 

$ kubectl get pods -A
NAMESPACE            NAME                                  READY   STATUS    RESTARTS       AGE
kube-system          coredns-bd6b6df9f-kqnfb               1/1     Running   1 (11h ago)    22h
kube-system          etcd-minikube                         1/1     Running   1 (11h ago)    22h
kube-system          kube-apiserver-minikube               1/1     Running   1 (128m ago)   22h
kube-system          kube-controller-manager-minikube      1/1     Running   1 (11h ago)    22h
kube-system          kube-proxy-tmsff                      1/1     Running   1 (11h ago)    22h
kube-system          kube-scheduler-minikube               1/1     Running   1 (128m ago)   22h
kube-system          storage-provisioner                   1/1     Running   3 (128m ago)   22h
pr-1234              nginx-deployment-9456bbbf9-h2fq2      1/1     Running   0              115m
pr-1234              nginx-deployment-9456bbbf9-jfqdk      1/1     Running   0              115m
pr-4321              nginx-pr-4321-5898bbdc5b-bk6zt        1/1     Running   0              2m12s
pr-4321              nginx-pr-4321-5898bbdc5b-kwv7d        1/1     Running   0              2m12s
py-kube-downscaler   py-kube-downscaler-75f695875f-gmxxh   1/1     Running   0              29s
```
[kube-downscaler-utc-tz.log](https://github.com/user-attachments/files/16424342/kube-downscaler-utc-tz.log)

So I think the exclude namespaces is working, haven't tested with regex, will do. But scale up isn't.
How do you think I can debug this?

**Comment by SohamChakraborty** [comment] 2024-07-30 10:09
Hurray @samuel-esp that worked out nicely. 
Thank you for following up. I will test some more and come back when I put it in our test cluster.

**Comment by samuel-esp** [comment] 2024-07-30 10:16
You're welcome, keep me updated! I will try to clarify the "overlapping timestamps" aspect inside the docs by the end of this week.

**Comment by SohamChakraborty** [comment] 2024-07-30 10:20
I will see if I can send a PR across to you. I guess some users might need something like that.

**Comment by samuel-esp** [comment] 2024-08-04 20:17
I've just made the pull request! #82

**Comment by samuel-esp** [comment] 2024-08-05 06:46
The pull request was merged, I'll close the issue!

**Closed by samuel-esp** 2024-08-05 06:46 UTC

**Comment by SohamChakraborty** [comment] 2024-08-06 06:34
@samuel-esp Thank you for the PR. I have one question about this. Let's say if we want to tweak the schedule on weekend and keep same schedule on the other weekdays, then does this following configuration work out?

```
rbac:
  create: true
arguments:
  - --include-resources=deployments
  - --debug
extraConfig: |
  EXCLUDE_NAMESPACES: "kube-system,argocd,default,ingress-nginx,jenkins,kube-node-lease,kube-public,py-kube-downscaler,sematext"
  DEFAULT_DOWNTIME: "Mon-Fri 23:31-23:59 Asia/Kolkata,Mon-Fri 00:00-09:30 Asia/Kolkata,Sat-Sun 00:20-23:59 Asia/Kolkata"
  DEFAULT_UPTIME: "Mon-Fri 09:31-23:30 Asia/Kolkata" 
```
So as you can see, we want to keep the entire weekend down. In this scenario is this right configuration? 

Also, another hypothetical :) Let's say that during the weekend, I want to work on any particular namespace that has been scaled down. Can I exclude that namespace in the `EXCLUDE_NAMESPACES` list and and redeploy with helm to make it up again?

Thanks for engaging in this conversation.

**Comment by samuel-esp** [comment] 2024-08-06 07:01
H @SohamChakraborty 

1. Yes that configuration should work, I would suggest you starting from 00:00 on Saturday and Sunday, not from 00:20 otherwise you could have a short uptime on both days
2. You can edit the configuration as you said, or you could use the annotations `downscaler/exclude` or `downscaler/exclude-until` at namespace level (see the docs for more details about these annotations). In general, Kube-Downscaler can be used in many different ways, so you can try them out and find the one that you like the most
